services:
  db:
    container_name: seats-db
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE='seats-db'
      - MYSQL_USER='seats'
      - MYSQL_PASSWORD='seat0310'
    ports:
      - "3306:3306"
    volumes:
      - seats-data:/var/lib/mysql

volumes:
  seats-data:
